#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WomenInBible.Droid.Resource", IsApplication=true)]

namespace WomenInBible.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::WomenInBible.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::WomenInBible.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alarm_off_32 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alarm_on_32 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_32 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int card1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int card10 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int card10a = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int card10b = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int card11 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int card11a = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int card11b = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int card12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int card12a = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int card12b = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int card1a = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int card1b = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int card2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int card2a = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int card2b = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int card3 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int card3a = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int card3b = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int card4 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int card4a = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int card4b = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int card5 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int card5a = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int card5b = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int card6 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int card6a = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int card6b = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int card7 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int card7a = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int card7b = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int card8 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int card8a = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int card8b = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int card9 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int card9a = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int card9b = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int clean_background = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int clock_32 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int disable_32 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int drawer_shadow = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int enable_32 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int events_32 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int fast_forward_32 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int forward_32 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int games_32 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_action_mail = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_overflow = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_overflow_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_search = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_drawer = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_launcher = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Icon = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int logo_01 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int magnifying_glass_32 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int map_pin_32 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int minus_32 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int monoandroidsplash = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int options_32 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int pause_32 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int plan_32 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int plus_32 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int rewind_32 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ringtone_32 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int set_date_32 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int set_time_32 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int settings_32 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int volume_32 = 2130837574;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
